name: "release"

on:
  repository_dispatch:
    types: [on-demand-release]
  workflow_dispatch:
    inputs:
      sha:
        description: "The SHA of the commit to build"
        required: true
        default: "main"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
            name: macOS arm64
          # - platform: macos-latest
          #   args: "--target x86_64-apple-darwin"
          #   name: macOS Intel
          # - platform: "windows-latest"
          #   args: ""
          #   name: Windows x64
          # - platform: "ubuntu-22.04" # must be the oldest version we want to support
          #   args: ""
          #   name: Linux x64
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          repository: liuzhch1/readcozy
          token: ${{ secrets.GH_TOKEN_FOR_CHECKOUT }}
          ref: ${{ github.event.client_payload.sha || (github.event.inputs.sha || 'main') }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10.27.0

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ contains(matrix.platform, 'macos') && 'aarch64-apple-darwin,x86_64-apple-darwin' || (contains(matrix.platform, 'ubuntu') && 'x86_64-unknown-linux-gnu' || 'x86_64-pc-windows-msvc') }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        if: matrix.platform != 'ubuntu-22.04'
        with:
          workspaces: ". -> target"

      - name: install dependencies
        run: pnpm install

      - name: build frontend
        run: pnpm --filter @readcozy/web build

      - name: generate icon
        working-directory: ./apps/desktop
        run: pnpm tauri icon ./icons/app-icon.png

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: ${{ !contains(matrix.platform, 'macos') }}
        with:
          projectPath: ./apps/desktop
          tauriScript: pnpm tauri
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "v__VERSION__"
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          repo: readcozy-releases
          owner: liuzhch1
          releaseCommitish: main
